
import java.io.File;
import java.io.IOException;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author yael
 */
public class componentePDF extends javax.swing.JFrame {

    /**
     * Creates new form componentePDF
     */
    public componentePDF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrearPDF.setAction(crearGenerarPDFAction());
        btnCrearPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnCrearPDF)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(btnCrearPDF)
                .addGap(129, 129, 129))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPDFActionPerformed

    }//GEN-LAST:event_btnCrearPDFActionPerformed
private Action crearGenerarPDFAction() {
    return new AbstractAction("Crear PDF") {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            try {
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setDialogTitle("Seleccione el archivo CSV");
                int seleccionCSV = fileChooser.showOpenDialog(null);

                if (seleccionCSV != JFileChooser.APPROVE_OPTION) {
                    System.out.println("No se seleccionó ningún archivo CSV.");
                    return;
                }
                File archivoCSV = fileChooser.getSelectedFile();

                fileChooser.setDialogTitle("Seleccione una imagen para el logo (opcional)");
                int seleccionLogo = fileChooser.showOpenDialog(null);
                File archivoLogo = (seleccionLogo == JFileChooser.APPROVE_OPTION) ? fileChooser.getSelectedFile() : null;

                fileChooser.setDialogTitle("Seleccione dónde guardar el archivo PDF");
                fileChooser.setSelectedFile(new File("factura.pdf"));
                int seleccionPDF = fileChooser.showSaveDialog(null);

                if (seleccionPDF != JFileChooser.APPROVE_OPTION) {
                    System.out.println("No se seleccionó ninguna ubicación de guardado.");
                    return;
                }
                File archivoPDF = fileChooser.getSelectedFile();

                ContenidoCSV contenidoCSV = new ContenidoCSV();
                contenidoCSV.cargarDesdeArchivo(archivoCSV);

                PDFGenerator pdfGenerator = new PDFGenerator();
                pdfGenerator.generarPDF(archivoPDF, archivoLogo, contenidoCSV);

                JOptionPane.showMessageDialog(null, "PDF generado exitosamente en: " + archivoPDF.getAbsolutePath());
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al generar el PDF: " + e.getMessage(), 
                                              "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    };
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(componentePDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(componentePDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(componentePDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(componentePDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new componentePDF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPDF;
    // End of variables declaration//GEN-END:variables
}
